### ISSUE TITLE
Enough stability for production use

### ISSUE THREAD

**Issue by jjangga0214** [ealmansi/set-interval-async#1]
Hi, this project interests me.  

Compared to [andyfleming/interval-promise (github)](https://github.com/andyfleming/interval-promise), I prefer **set-interval-async** bit more as it provides two strategies, "fixed" and "dynamic", although [interval-promise (npm)](https://www.npmjs.com/package/interval-promise) has much higher download frequency (1613 weekly downloads at the time of writing) .  

However, **set-interval-async** is on VERY early stage, so it is quite hesitating to use on production. 

Well, though generally it's highly recommended not to use too new modules, but I am not too strict to such a philosophy if the project is enough simple and tested thoroughly. 

Before making decision, I'd like to ask weather you think this project is tested well and can be used and promised to be updated (in future) in stable way even for production environment. 

P.S. Why do you recommend using exact version(`yarn add -E`)? Is it to prevent broken update even if you made a mistake that breaks SemVer?

**Comment by ealmansi** [comment]
Hi @jjangga0214 , thanks for your interest in `set-interval-async`.

Regarding stability, this library is small and has a simple goal: to provide a drop-in replacement for `setInterval` that can be used safely with asynchronous code. Since keeping API compatibility with vanilla `setInterval` is a requirement, there will be no future breaking changes added to this library's API. Only bug fixes will be merged, in case any bugs are reported.

The library is indeed very new. However, it is also thoroughly tested, has 100% [code coverage](https://coveralls.io/github/ealmansi/set-interval-async?branch=master), and is rather simple - in case you'd like to audit the code.

I hope you find `set-interval-async` very easy to use, and that it solves your problem so that you can move on to building your app.

PS: In my opinion, exact versions should be the default, at least for security critical applications. Upgrading dependencies should be a careful and manual process, and be done only on-demand, since there is always a security risk involved.
