### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by dontevenblink** [ealmansi/set-interval-async#17]
Hello all. I just tried to bring set-interval-async into the browser and I'm getting the following error in the chrome console:

"DevTools failed to load SourceMap: Could not load content for https://unpkg.com/set-interval-async.iife.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"

I put this line from the documentation into my <head></head>: 

<script src="https://unpkg.com/set-interval-async"></script>

I've only used set-interval-async before in node. Anyone know what is going on here?

**Comment by ealmansi** [comment]
Hi @dontevenblink, thanks for creating this issue.

It looks like it was some transient downtime on unpkg.com. Including the library in a script tag like you wrote above is currently working.

For a production app you would probably want to use an app bundler like Webpack to download the code and build it into your app rather than using the script tag and depending on unpkg.com being available.
