### ISSUE TITLE
Question regarding clearIntervalAsync

### ISSUE THREAD

**Issue by wouterhund** [ealmansi/set-interval-async#3]
Hello,

We are planning to use this application in a React Native application, where performing `setInterval` or `setTimeout` with a large interval is discouraged (https://github.com/facebook/react-native/issues/12981). This isn't a problem, except for the following code in `clear.js`:

```
  const noopInterval = setInterval(noop, MAX_INTERVAL_MS)
  await Promise.all(promises)
  clearInterval(noopInterval)
```

Which gives us a warning. Now I'm wondering, what is the purpose of this noopInterval?

It also seems that this noopInterval won't be cleared if any of the promises throw during `await Promise.all`, so perhaps using a try/finally block would be appropriate.

Thanks!

**Comment by ealmansi** [comment]
Hi @wouterhund ,

Thanks a lot for raising this issue. It looks like the warning on React Native got removed since you wrote:

https://github.com/facebook/react-native/commit/480dabd66547a60522249eda203a3eb1934b02e5

I've also reduced the noop interval in this library to avoid the warning for anyone stuck older versions of RN. Either way, it should have no functional impact on this library at all.

> It also seems that this noopInterval won't be cleared if any of the promises throw during await Promise.all, so perhaps using a try/finally block would be appropriate.

Exactly. However, that's why all promises in that array are appended with a `.catch(noop)` earlier in the same function.
